### ISSUE TITLE
More verbose DEVELOPMENT options

### ISSUE THREAD

**Issue by Pegasuz** [dockerwest/php#1]
Right now the only options for the DEVELOPMENT options are:

- noprofile: only activate xdebug
- 1: activate everything

The only possibility to disable every development option is to not set this variable.
When using the compose environments, this option is set through the .env file.

It would be great to be able to disable every development option by setting the DEVELOPMENT to '0' or so.

Also, maybe 'noprofile' is not so clear to everyone? Can we make this more clear by changing this name? eg. "xdebug", "default", "noprofiling", ...

**Comment by Pegasuz** [comment]
We will split up the DEVELOPMENT option:

DEBUG=xdebug|whatever|...
PROFILER=xhprof|tideways|blackfire

if debug or profiler is set with a not supported option, it will be disabled.

**Comment by BlackIkeEagle** [comment]
profiler should also have a xdebug option

**Comment by BlackIkeEagle** [comment]
has been implemented a while ago
