### ISSUE TITLE
Problem with default php version on 5.6 image

### ISSUE THREAD

**Issue by ghost** [dockerwest/php#5]
Hi,

**PROBLEM**

I discovered problem with php in version 5.6. By default the main version inside image is php 7.3, not 5.6 and tasks inside all commands are running with that version. With images 7.0 and later everything is fine

**STEPS TO REPRODUCE**

You need to run docker image with simple command to reproduce problem.

Info about default php version:
`docker run dockerwest/php:5.6 php -v`
Info about alternatives:
`docker run dockerwest/php:5.6 update-alternatives --display php`

**EXPECTED RESULT**

For the first command it should look like this:
> PHP 5.6.40-12+0~20190902.20+debian9~1.gbpc72558 (cli) 
> Copyright (c) 1997-2016 The PHP Group
> Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
>     with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

For the second one it should look like this:
> php - auto mode
>   link best version is /usr/bin/php5.6
>   link currently points to /usr/bin/php5.6
>   link php is /usr/bin/php
>   slave php.1.gz is /usr/share/man/man1/php.1.gz
> /usr/bin/php5.6 - priority 56
>   slave php.1.gz: /usr/share/man/man1/php5.6.1.gz

**ACTUAL RESULT**

> docker run dockerwest/php:5.6 php -v
> PHP 7.3.9-1+0~20190902.44+debian9~1.gbpf8534c (cli) (built: Sep  2 2019 13:31:30) ( NTS )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
>     with Zend OPcache v7.3.9-1+0~20190902.44+debian9~1.gbpf8534c, Copyright (c) 1999-2018, by Zend Technologies

> docker run dockerwest/php:5.6 update-alternatives --display php
> php - auto mode
>   link best version is /usr/bin/php7.3
>   link currently points to /usr/bin/php7.3
>   link php is /usr/bin/php
>   slave php.1.gz is /usr/share/man/man1/php.1.gz
> /usr/bin/php5.6 - priority 56
>   slave php.1.gz: /usr/share/man/man1/php5.6.1.gz
> /usr/bin/php7.3 - priority 73
>   slave php.1.gz: /usr/share/man/man1/php7.3.1.gz

I don't know how to fix this issue, but for now I'm creating alternative in `prepare-command.sh` with higher priority than php 7.3 to get rid of this problem.
I also don't understand why there php 7.3 is a default php in this image.

Thank you for your help with that case. If you have any additional questions just let me know.

**Comment by BlackIkeEagle** [comment]
hi @wszychta I'm looking into it, probably something got broken in the upstream php repo of ondrej sury.
